homepage: "https://gdal.org"
language: c++
primary_contact: "even.rouault@gmail.com"
auto_ccs:
  - "schwehr@gmail.com"
  - "mateusz@loskot.net"
  - "bishop.dev@gmail.com"
  - "juergen.fischer@gmail.com"
  - "athomas@thinkspatial.com.au"
  - "ari.jolma@gmail.com"
  - "bjorn.harrtell@gmail.com"
  - "nyall.dawson@gmail.com"
architectures:
  - x86_64
  - i386
main_repo: 'https://github.com/OSGeo/gdal'
additional_vars:
  all:
    SYSTEMSAN_ARBITRARY_DNS_RESOLUTION=0
