fuzzing_engines:
- libfuzzer
homepage: https://github.com/certifi/python-certifi
language: python
main_repo: https://github.com/certifi/python-certifi
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
